// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Produto struct {
	ID              int64          `json:"id"`
	CodigoBarras    sql.NullInt64  `json:"codigo_barras"`
	Nome            string         `json:"nome"`
	Descricao       sql.NullString `json:"descricao"`
	Foto            sql.NullString `json:"foto"`
	Valorpago       int64          `json:"valorpago"`
	Valorvenda      int64          `json:"valorvenda"`
	Qtde            int64          `json:"qtde"`
	UndCod          sql.NullInt64  `json:"und_cod"`
	CatCod          sql.NullInt64  `json:"cat_cod"`
	ScatCod         sql.NullInt64  `json:"scat_cod"`
	DataCriacao     time.Time      `json:"data_criacao"`
	DataAtualizacao sql.NullTime   `json:"data_atualizacao"`
}
