// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type Cliente struct {
	ID              string         `json:"id"`
	Nome            string         `json:"nome"`
	Email           string         `json:"email"`
	Cpf             sql.NullString `json:"cpf"`
	Fone            sql.NullInt32  `json:"fone"`
	Foto            sql.NullString `json:"foto"`
	Sexo            sql.NullString `json:"sexo"`
	DataNascimento  sql.NullTime   `json:"data_nascimento"`
	DataCriacao     time.Time      `json:"data_criacao"`
	DataAtualizacao sql.NullTime   `json:"data_atualizacao"`
}

type Produto struct {
	ID              int64        `json:"id"`
	CodigoBarras    int64        `json:"codigo_barras"`
	Nome            string       `json:"nome"`
	Descricao       string       `json:"descricao"`
	Foto            string       `json:"foto"`
	Valorpago       int64        `json:"valorpago"`
	Valorvenda      int64        `json:"valorvenda"`
	Qtde            int64        `json:"qtde"`
	UndCod          int64        `json:"und_cod"`
	CatCod          int64        `json:"cat_cod"`
	ScatCod         int64        `json:"scat_cod"`
	DataCriacao     time.Time    `json:"data_criacao"`
	DataAtualizacao sql.NullTime `json:"data_atualizacao"`
}
