// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type Cliente struct {
	ID              int64        `json:"id"`
	Nome            string       `json:"nome"`
	Email           string       `json:"email"`
	Cpf             string       `json:"cpf"`
	Fone            int64        `json:"fone"`
	Foto            string       `json:"foto"`
	Sexo            string       `json:"sexo"`
	DataNascimento  time.Time    `json:"data_nascimento"`
	DataCriacao     time.Time    `json:"data_criacao"`
	DataAtualizacao sql.NullTime `json:"data_atualizacao"`
}

type Produto struct {
	ID              int64        `json:"id"`
	CodigoBarras    int64        `json:"codigo_barras"`
	Nome            string       `json:"nome"`
	Descricao       string       `json:"descricao"`
	Foto            string       `json:"foto"`
	Valorpago       float64      `json:"valorpago"`
	Valorvenda      float64      `json:"valorvenda"`
	Qtde            int64        `json:"qtde"`
	UndCod          int64        `json:"und_cod"`
	CatCod          int64        `json:"cat_cod"`
	ScatCod         int64        `json:"scat_cod"`
	DataCriacao     time.Time    `json:"data_criacao"`
	DataAtualizacao sql.NullTime `json:"data_atualizacao"`
}
