// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduto(ctx context.Context, arg CreateProdutoParams) (Produto, error)
	DeleteProduto(ctx context.Context, id int64) error
	GetProduto(ctx context.Context, id int64) (Produto, error)
	ListProdutos(ctx context.Context, arg ListProdutosParams) ([]Produto, error)
	UpdateProduto(ctx context.Context, arg UpdateProdutoParams) (Produto, error)
}

var _ Querier = (*Queries)(nil)
