// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateCliente(ctx context.Context, arg CreateClienteParams) (Cliente, error)
	CreateProduto(ctx context.Context, arg CreateProdutoParams) (Produto, error)
	DeleteCliente(ctx context.Context, id int64) error
	DeleteProduto(ctx context.Context, id int64) error
	GetCliente(ctx context.Context, nome string) (Cliente, error)
	GetProduto(ctx context.Context, codigoBarras int64) (Produto, error)
	ListClientes(ctx context.Context, arg ListClientesParams) ([]Cliente, error)
	ListProdutos(ctx context.Context, arg ListProdutosParams) ([]Produto, error)
	UpdateCliente(ctx context.Context, arg UpdateClienteParams) (Cliente, error)
	UpdateProduto(ctx context.Context, arg UpdateProdutoParams) (Produto, error)
}

var _ Querier = (*Queries)(nil)
